### ISSUE TITLE
build the project , Prompt warning： bCastDynamicShadow设为false

### ISSUE THREAD

**Issue by lishu2006ll** [CesiumGS/cesium-unreal#872]
when I build the project ,  prompt the fllower warning, How to solve this problem 
https://assets.cesium.com/1/3/13/4.terrain?v=1.2.0&extensions=octvertexnormals-metadata mesh 0 primitive 0 除非将bCastDynamicShadow设为false，否则大型actor将接收预投影，并会导致极大的性能开销。 
https://assets.cesium.com/1/3/12/5.terrain?v=1.2.0&extensions=octvertexnormals-metadata mesh 0 primitive 0 除非将bCastDynamicShadow设为false，否则大型actor将接收预投影，并会导致极大的性能开销。 
https://assets.cesium.com/1/3/13/5.terrain?v=1.2.0&extensions=octvertexnormals-metadata mesh 0 primitive 0 除非将bCastDynamicShadow设为false，否则大型actor将接收预投影，并会导致极大的性能开销。 
https://assets.cesium.com/1/2/7/2.terrain?v=1.2.0&extensions=octvertexnormals-metadata mesh 0 primitive 0 除非将bCastDynamicShadow设为false，否则大型actor将接收预投影，并会导致极大的性能开销。 

![image](https://user-images.githubusercontent.com/3477402/172770533-2e70e9d6-e1f1-42dc-8f09-6560d48c38ef.png)

**Comment by kring** [comment]
I believe this has been fixed for a long time now.

**Comment by AnnabelGENG** [comment]
still exists

![Image](https://github.com/user-attachments/assets/f6abf892-7e22-4370-9798-31827508bfb6)

**Comment by kring** [comment]
@AnnabelGENG what version of Unreal Engine and Cesium for Unreal are you using there?
The Cesium for Unreal version is found in the lower-right corner of the Cesium panel.
